apiVersion: v1
kind: Service
metadata:
  name: cfn
  labels:
    app: cfn
spec:
  ports:
  - port: 9002
    name: http
  selector:
    app: cfn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfn
  template:
    metadata:
      labels:
        app: cfn
    spec:
      containers:
      - name: cfn
        image: sidecar-standalone-cfn:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9002
        env:
        - name: PORT
          value: "9002"
