name: CI - Lint and Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checkout-unit-tests:
    name: Checkout & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.ref }}
          clean: true

      - name: Install uv
        uses: astral-sh/setup-uv@d0d8abe699bfb85fec6de9f7adb5ae17292296ff # v6
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"

      - name: Unit Tests
        run: bash scripts/unit-test.sh

  reusable-workflow-ci-status:
    name: CI Status
    needs: [checkout-unit-tests]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        if: ${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
        run: |
          echo "*** WORKFLOW FAILED ***"
          exit 1
      - name: Success
        run: |
          echo "*** WORKFLOW SUCCESS ***"
